trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.1
  GITHUB_REPO: 'https://github.com/rnbruno/pestex_.git'  # Substitua pelo seu repositório
  GITHUB_USERNAME: 'rnbruno'  # Seu nome de usuário no GitHub

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    # Configure git
    git config --global user.email "brunosmatias@gmail.com"
    git config --global user.name "rnbruno"
    
    # Add, commit, and push changes
    git add .
    git commit -m "Automated commit from Azure DevOps pipeline"
    
    # Push changes to the GitHub repository
    git push https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@$(GITHUB_REPO) HEAD:main
  displayName: 'Commit and Push Changes'
